name: Deploy Unity Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          cp .github/known_hosts ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add Cache-Busting Version
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/UnityLoader.js.*/UnityLoader.js?v=$TIMESTAMP/" ./Data/index.html
          sed -i "s/style.css.*/style.css?v=$TIMESTAMP/" ./Data/index.html

      - name: Deploy files to server
        run: |
          rsync -avz --delete ./Data/ root@164.92.253.209:/var/www/biztycoongame